@php($initialBlocks = old('blocks', $page->blocks ?? []))
<div class="bg-white rounded-xl border border-gray-200 p-6" x-data="pageBlocks(@js($initialBlocks))">
    <div class="flex flex-wrap items-center justify-between gap-3 mb-5">
        <div><h3 class="font-semibold text-gray-900">Page sections</h3><p class="text-xs text-gray-500 mt-1">Add and reorder the sections visitors see.</p></div>
        <select x-model="newType" class="form-control-modern w-auto text-sm"><option value="">Add block…</option><template x-for="type in types"><option :value="type" x-text="labels[type]"></option></template></select>
        <button type="button" @click="add()" class="btn btn-secondary btn-sm" :disabled="!newType">Add</button>
    </div>
    <div class="space-y-4">
        <template x-for="(block, index) in blocks" :key="block.id">
            <section class="border border-surface-200 rounded-xl overflow-hidden">
                <div class="px-4 py-3 bg-surface-50 flex items-center gap-3"><span class="text-xs font-bold uppercase tracking-wider text-gray-500" x-text="labels[block.type]"></span><span class="ml-auto flex gap-1"><button type="button" @click="move(index,-1)" :disabled="index===0" class="p-1 text-gray-500 disabled:opacity-30" aria-label="Move up">↑</button><button type="button" @click="move(index,1)" :disabled="index===blocks.length-1" class="p-1 text-gray-500 disabled:opacity-30" aria-label="Move down">↓</button><button type="button" @click="blocks.splice(index,1)" class="p-1 text-red-600" aria-label="Remove block">×</button></span></div>
                <div class="p-4 space-y-3">
                    <input type="hidden" :name="`blocks[${index}][type]`" :value="block.type">
                    <template x-if="block.type === 'hero'"><div class="grid sm:grid-cols-2 gap-3"><input :name="`blocks[${index}][data][eyebrow]`" x-model="block.data.eyebrow" placeholder="Eyebrow" class="form-control-modern"><input :name="`blocks[${index}][data][title]`" x-model="block.data.title" placeholder="Headline" class="form-control-modern"><textarea :name="`blocks[${index}][data][subtitle]`" x-model="block.data.subtitle" placeholder="Subtitle" class="form-control-modern sm:col-span-2"></textarea><input :name="`blocks[${index}][data][image]`" x-model="block.data.image" placeholder="Media path (e.g. pages/hero.jpg)" class="form-control-modern sm:col-span-2"></div></template>
                    <template x-if="block.type === 'rich_text'"><div class="space-y-3"><input :name="`blocks[${index}][data][heading]`" x-model="block.data.heading" placeholder="Section heading" class="form-control-modern"><textarea rows="7" :name="`blocks[${index}][data][body]`" x-model="block.data.body" placeholder="Text; basic headings, paragraphs and lists are allowed." class="form-control-modern"></textarea></div></template>
                    <template x-if="block.type === 'image'"><div class="grid sm:grid-cols-2 gap-3"><div><input :name="`blocks[${index}][data][path]`" x-model="block.data.path" placeholder="Media path" class="form-control-modern"><a href="{{ route('admin.media.index') }}" target="_blank" class="mt-1 inline-block text-xs font-semibold text-primary-600">Open Media Library</a></div><input :name="`blocks[${index}][data][alt]`" x-model="block.data.alt" placeholder="Alternative text" class="form-control-modern"><input :name="`blocks[${index}][data][caption]`" x-model="block.data.caption" placeholder="Caption" class="form-control-modern sm:col-span-2"></div></template>
                    <template x-if="block.type === 'cta'"><div class="grid sm:grid-cols-2 gap-3"><input :name="`blocks[${index}][data][heading]`" x-model="block.data.heading" placeholder="Heading" class="form-control-modern"><input :name="`blocks[${index}][data][label]`" x-model="block.data.label" placeholder="Button label" class="form-control-modern"><textarea :name="`blocks[${index}][data][text]`" x-model="block.data.text" placeholder="Supporting text" class="form-control-modern"></textarea><input :name="`blocks[${index}][data][url]`" x-model="block.data.url" placeholder="/get-a-quote or https://…" class="form-control-modern"></div></template>
                    <template x-if="block.type === 'collection'"><div class="grid sm:grid-cols-3 gap-3"><input :name="`blocks[${index}][data][heading]`" x-model="block.data.heading" placeholder="Heading" class="form-control-modern"><select :name="`blocks[${index}][data][source]`" x-model="block.data.source" class="form-control-modern"><option value="services">Services</option><option value="portfolio">Portfolio</option><option value="products">Products</option><option value="testimonials">Testimonials</option></select><input type="number" min="1" max="12" :name="`blocks[${index}][data][limit]`" x-model="block.data.limit" class="form-control-modern"></div></template>
                    <template x-if="block.type === 'stats'"><div><div class="flex justify-between mb-3"><p class="text-sm font-semibold">Statistics</p><button type="button" @click="block.data.items.push({value:'',label:''})" class="text-xs font-bold text-primary-600">Add stat</button></div><template x-for="(item, itemIndex) in (block.data.items || [])" :key="itemIndex"><div class="grid grid-cols-[1fr_1fr_auto] gap-2 mb-2"><input :name="`blocks[${index}][data][items][${itemIndex}][value]`" x-model="item.value" placeholder="10k+" class="form-control-modern"><input :name="`blocks[${index}][data][items][${itemIndex}][label]`" x-model="item.label" placeholder="Projects delivered" class="form-control-modern"><button type="button" @click="block.data.items.splice(itemIndex,1)" class="text-red-600 px-2">×</button></div></template></div></template>
                    <template x-if="block.type === 'faq'"><div><div class="flex justify-between mb-3"><p class="text-sm font-semibold">Questions and answers</p><button type="button" @click="block.data.items.push({question:'',answer:''})" class="text-xs font-bold text-primary-600">Add question</button></div><template x-for="(item, itemIndex) in (block.data.items || [])" :key="itemIndex"><div class="grid grid-cols-[1fr_auto] gap-2 mb-3"><input :name="`blocks[${index}][data][items][${itemIndex}][question]`" x-model="item.question" placeholder="Question" class="form-control-modern"><button type="button" @click="block.data.items.splice(itemIndex,1)" class="text-red-600 px-2">×</button><textarea :name="`blocks[${index}][data][items][${itemIndex}][answer]`" x-model="item.answer" placeholder="Answer" class="form-control-modern col-span-2"></textarea></div></template></div></template>
                </div>
            </section>
        </template>
        <p x-show="!blocks.length" class="py-6 text-center text-sm text-gray-400 border border-dashed border-surface-300 rounded-xl">No blocks yet. Add a section above.</p>
    </div>
</div>
@push('scripts')<script>function pageBlocks(initial){return {blocks:initial||[],newType:'',types:['hero','rich_text','image','cta','stats','faq','collection'],labels:{hero:'Hero',rich_text:'Rich text',image:'Image',cta:'Call to action',stats:'Stats',faq:'FAQ',collection:'Content collection'},add(){if(!this.newType)return;this.blocks.push({id:Date.now()+'-'+Math.random(),type:this.newType,data:this.defaults(this.newType)});this.newType=''},move(i,d){let n=i+d;if(n<0||n>=this.blocks.length)return;[this.blocks[i],this.blocks[n]]=[this.blocks[n],this.blocks[i]]},defaults(t){return t==='collection'?{source:'services',heading:'',limit:3}:t==='faq'||t==='stats'?{items:[]}: {}}}}</script>@endpush
